"""
MOCK AGENT FOR TESTING
----------------------
This is a stand-in file created for testing the Charm SDK.
"""

import json

# 1. Define a Mock Crew class
class MockCrew:
    """Simulates a CrewAI Crew object."""
    
    def __init__(self):
        self.agents = ["Project Analyst", "Resource Searcher", "Coding Agent"]
        self.tasks = ["Analysis", "Search", "Coding"]

    def kickoff(self, inputs=None):
        """
        Simulates the real kickoff behavior.
        Returns a successful mock report regardless of the input.
        """
        print(f"[MockCrew] Kickoff called with inputs: {inputs}")
        
        # Simulate the Markdown report typically generated by the original script
        mock_report = """
# Project Analysis (MOCK RESULT)

## Summary
This is a simulated output generated by the test fixture.
The Charm SDK successfully loaded and executed this agent.

## Risks
1. Dependency on external APIs
2. Token limits

## Recommendations
- Use Charm for orchestration
- Keep agents atomic
"""
        
        return type('CrewOutput', (), {'raw': mock_report})

# This corresponds to the setting in your charm.yaml:
# entry_point: "crewai_research_agent:crew_instance"

crew_instance = MockCrew()

# Create an alias if the real code uses the variable name 'crew'
crew = crew_instance

if __name__ == "__main__":
    print("Mock Agent loaded successfully.")