name: Build Runtime Images (Production)

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'Dockerfile*'

env:
    PROJECT_ID: charm-cloud-runner
    REGION: us-central1
    REPO_NAME: charm-images

permissions:
    contents: 'read'
    id-token: 'write'

jobs:
    build-runtimes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v2'
              with:
                  workload_identity_provider: 'projects/684785328850/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
                  service_account: 'github-deployer-prod@charm-cloud-runner-prod.iam.gserviceaccount.com'

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v2"

            - name: "Configure Docker"
              run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

            - name: "Build & Push Standard Image"
              run: |
                  docker build -f Dockerfile.standard -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/runner-standard:prod .
                  docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/runner-standard:prod

            - name: "Build & Push Full Image"
              run: |
                  docker build -f Dockerfile.full -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/runner-full:prod .
                  docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/runner-full:prod
