name: Trigger Runner Deploy

on:
    push:
        branches:
            - develop

jobs:
    notify-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Runner Workflow
              run: |
                gh workflow run deploy-staging.yml \
                  --repo CharmAIOS/charm-cloud-runner \
                  --ref develop
              env:
                GH_TOKEN: ${{ secrets.SDK_PAT_TOKEN }}
